CREATE TABLE `data_platform_game_header_data`
(
  `Game`                             int(16) NOT NULL,
  `GameType`                         varchar(4) NOT NULL,
  `GameOwner`                        int(12) NOT NULL,
  `GameOwnerBusinessPartnerRole`     varchar(40) NOT NULL,
  `PersonResponsible`                varchar(40) NOT NULL,
  `ValidityStartDate`                date NOT NULL,
  `ValidityStartTime`                time NOT NULL,
  `ValidityEndDate`                  date NOT NULL,
  `ValidityEndTime`                  time NOT NULL,
  `OperationStartDate`               date NOT NULL,
  `OperationStartTime`               time NOT NULL,
  `OperationEndDate`                 date NOT NULL,
  `OperationEndTime`                 time NOT NULL,
  `Description`                      varchar(60) NOT NULL,
  `LongText`                         varchar(1000) NOT NULL,
  `Introduction`                     varchar(200) DEFAULT NULL,
  `Site`                             int(16) NOT NULL,
  `Project`                          int(16) DEFAULT NULL,
  `WBSElement`                       int(8) DEFAULT NULL,
  `Tag1`                             varchar(40) DEFAULT NULL,
  `Tag2`                             varchar(40) DEFAULT NULL,
  `Tag3`                             varchar(40) DEFAULT NULL,
  `Tag4`                             varchar(40) DEFAULT NULL,
  `DistributionProfile`              varchar(4) NOT NULL,
  `PointConditionType`               varchar(4) NOT NULL,
  `QuestionnaireType`                varchar(4) DEFAULT NULL,
  `QuestionnaireTemplate`            varchar(4) DEFAULT NULL,
  `CreationDate`                     date NOT NULL,
  `CreationTime`                     time NOT NULL,
  `LastChangeDate`                   date NOT NULL,
  `LastChangeTime`                   time NOT NULL,
  `CreateUser`                       int(12) NOT NULL,
  `LastChangeUser`                   int(12) NOT NULL,
  `IsReleased`                       tinyint(1) DEFAULT NULL,
  `IsCancelled`                      tinyint(1) DEFAULT NULL,
  `IsMarkedForDeletion`              tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Game`),

    CONSTRAINT `DPFMGameHeaderDataGameType_fk` FOREIGN KEY (`GameType`) REFERENCES `data_platform_game_type_game_type_data` (`GameType`),
    CONSTRAINT `DPFMGameHeaderDataGameOwner_fk` FOREIGN KEY (`GameOwner`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMGameHeaderDataGameOwnerBPRole_fk` FOREIGN KEY (`GameOwnerBusinessPartnerRole`) REFERENCES `data_platform_bp_role_bp_role_data` (`BusinessPartnerRole`),
    CONSTRAINT `DPFMGameHeaderDataSite_fk` FOREIGN KEY (`Site`) REFERENCES `data_platform_site_header_data` (`Site`),
    CONSTRAINT `DPFMGameHeaderDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`),
    CONSTRAINT `DPFMGameHeaderDataWBSElement_fk` FOREIGN KEY (`Project`, `WBSElement`) REFERENCES `data_platform_project_wbs_element_data` (`Project`, `WBSElement`),
    CONSTRAINT `DPFMGameHeaderDataDistributionProfile_fk` FOREIGN KEY (`DistributionProfile`) REFERENCES `data_platform_distribution_profile_distribution_profile_data` (`DistributionProfile`),
    CONSTRAINT `DPFMGameHeaderDataPointConditionType_fk` FOREIGN KEY (`PointConditionType`) REFERENCES `data_platform_point_condition_type_point_condition_type_data` (`PointConditionType`),
    CONSTRAINT `DPFMGameHeaderDataQuestionnaireType_fk` FOREIGN KEY (`QuestionnaireType`) REFERENCES `data_platform_questionnaire_type_questionnaire_type_data` (`QuestionnaireType`),
    CONSTRAINT `DPFMGameHeaderDataQuestionnaireTemplate_fk` FOREIGN KEY (`QuestionnaireTemplate`) REFERENCES `data_platform_questionnaire_tmpl_questionnaire_tmpl_data` (`QuestionnaireTemplate`),
    CONSTRAINT `DPFMGameHeaderDataCreateUser_fk` FOREIGN KEY (`CreateUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DPFMGameHeaderDataLastChangeUser_fk` FOREIGN KEY (`LastChangeUser`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
